Repository msfjarvis/viscerion, pull requests merged in 2019-10, with the labels that each got.

#179 Add search for tunnels
  app/src/main/java/com/wireguard/android/fragment/TunnelDetailFragment.kt
  app/src/main/java/com/wireguard/android/fragment/TunnelListFragment.kt
  app/src/main/res/drawable/ic_action_search.xml
  app/src/main/res/menu/main_activity.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/searchable.xml
Labels: PR: reviewed-approved

#180 New Crowdin translations
  app/src/main/res/values-de/strings.xml
Labels: PR: unreviewed

#181 New Crowdin translations
  app/src/main/res/values-fr/strings.xml
Labels: PR: unreviewed

#193 Completely remove buildSrc
  app/build.gradle
  build.gradle
  buildSrc/.gitignore
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/Libs.kt
  buildSrc/src/main/kotlin/VersionConfiguration.kt
  buildSrc/src/main/kotlin/Versions.kt
  crypto/build.gradle
  native/build.gradle
  spotless.gradle
  spotless.root.gradle
  versions.gradle
Labels: PR: unreviewed

#190 Add native Tasker integation
  CHANGELOG.md
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/wireguard/android/activity/TaskerActivity.kt
  app/src/main/java/com/wireguard/android/model/TunnelManager.kt
  app/src/main/java/com/wireguard/android/services/TaskerIntegrationReceiver.kt
  app/src/main/res/layout/tasker_activity.xml
  app/src/main/res/values/strings.xml
Labels: PR: reviewed-approved, enhancement, hacktoberfest

#195 New Crowdin translations
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-fr/strings.xml
Labels: PR: unreviewed

#197 Re-add GitHub Actions workflows
  .github/workflows/build.yml
  .github/workflows/greetings.yml
  .github/workflows/stale.yml
  README.md
  app/build.gradle
Labels: PR: unreviewed
